lesson 6 homework
antdolg1/jg_java_1_thursday_august_2023 pull request #26
Opened 2023-09-26 11:15 UTC by denis-vil

lesson 6 homework

2023-11-11 12:04 UTC, antdolg1 commented on src/main/java/students/denis_asipenka/lesson_6/level_3/ArrayService.java
> +    int CountingOccurrences(int[] arr, int number) {
```suggestion
    int countingOccurrences(int[] arr, int number) {
```

2023-11-11 12:53 UTC, antdolg1 commented on src/main/java/students/denis_asipenka/lesson_6/level_3/ArrayService.java
> +    }
1. Этот метод не делает то, что требовалось в задании. В задании требовалось пройти по массиву и заменить первое вхождение указанного числа в массиве на другое число. 
2. Ты итерируешь по массиву не с начала, а с конца. К тому же у тебя есть ошибка, согласно твоему условию в цикле ты пропускаешь самый первый элемент массива с индексом 0.
3. В переменной result нет особого смысла, так как ты сразу можешь возвращать true или false.
4. Я понял твою идею, но скажу честно что это очень запутанное решение и не оптимальное. Эту задачу можно решить гораздо проще и более прямолинейно. Например:

```
boolean replaceFirst(int[] arr, int oldNumber, int newNumber) {
    for (int i = 0; i < arr.length; i++) {
        if (arr[i] == oldNumber) {
            arr[i] = newNumber;
            return true;
        }
    }
    return false;
}
```

2023-11-11 12:54 UTC, antdolg1 commented on src/main/java/students/denis_asipenka/lesson_6/level_3/ArrayService.java
> +    }
1. Этот метод не делает то, что требовалось в задании. В задании требовалось пройти по массиву и заменить первое вхождение указанного числа в массиве на другое число.
2. Ты итерируешь по массиву не с начала, а с конца. К тому же у тебя есть ошибка, согласно твоему условию в цикле ты пропускаешь самый первый элемент массива с индексом 0.
3. В переменной result нет особого смысла, так как ты сразу можешь возвращать true или false.

В целом я понял твою идею, но скажу честно что это очень запутанное решение и не оптимальное. Эту задачу можно решить гораздо проще и более прямолинейно. Например:

```
boolean replaceFirst(int[] arr, int oldNumber, int newNumber) {
    for (int i = 0; i < arr.length; i++) {
        if (arr[i] == oldNumber) {
            arr[i] = newNumber;
            return true;
        }
    }
    return false;
}
```

Пожалуйста исправь код и юнит тест.

2023-11-11 12:58 UTC, antdolg1 commented on src/main/java/students/denis_asipenka/lesson_6/level_3/ArrayServiceTest.java
> +    void replaceArrayTest() {
Ты тестируешь метод reverseArray, а тест называет replaceArrayTest, что не совсем верно.

2023-11-11 13:25 UTC, antdolg1 requested changes
See my comments.

2023-11-12 09:54 UTC, denis-vil commented
Вчера поправил вроде как все, и запросил проверку еще раз. Дублирую комментарием, если не отобразилось

2023-12-12 09:11 UTC, antdolg1 approved these changes

2023-12-12 09:11 UTC, merged